### LOJA

###
POST http://localhost:8080/compra
Content-Type: application/json

{
    "itens":[
        {
            "id":1,
            "quantidade":5
        },
        {
            "id":2,
            "quantidade":10
        }
    ],
    "endereco":{
        "rua":"Rua das Jabuticabas",
        "numero":12313,
        "estado":"SP"
    }
}


###
GET http://localhost:8080/compra/2
 
### EUREKA APPS

###
GET http://localhost:8761/eureka/apps
 
### Config-Server Fornecedor

###
GET http://localhost:8888/fornecedor/default

###
GET http://localhost:5555/actuator/routes

###
GET http://localhost:5555/fornecedor/info/SP

###
POST http://localhost:5555/loja/compra
Content-Type: application/json

{
    "itens":[
        {
            "id":1,
            "quantidade":5
        },
        {
            "id":2,
            "quantidade":10
        }
    ],
    "endereco":{
        "rua":"Rua das Jabuticabas",
        "numero":12313,
        "estado":"SP"
    }
}

###
POST http://localhost:8088/oauth/token
Authorization: Basic loja lojapwd
Content-Type: application/x-www-form-urlencoded

scope=web&grant_type=password&username=joao&password=joaopwd


###
GET http://localhost:8088/user
Authorization: dc01bed5-05cc-4fc2-9185-e8abc7d212b6
