POST http://localhost:8080/compra
Content-Type: application/json

{
    "itens":[
        {
            "id":1,
            "quantidade":5
        },
        {
            "id":2,
            "quantidade":10
        }
    ],
    "endereco":{
        "rua":"Rua das Jabuticabas",
        "numero":1231,
        "estado":"SP"
    }
}