POST http://localhost:8080/compra
Content-Type: application/json

{
    "itens":[
        {
            "id":1,
            "quantidade":5
        },
        {
            "id":2,
            "quantidade":10
        }
    ],
    "endereco":{
        "rua":"Rua das Jabuticabas",
        "numero":1231,
        "estado":"SP"
    }
}

###
GET http://localhost:8081/info/SP
Content-Type: application/json

 
### EUREKA APPS

###
GET http://localhost:8761/eureka/apps
 
### Config-Server Fornecedor

###
GET http://localhost:8888/fornecedor/default